# 1. Introducción


* Breve descripción general de Pandas y su importancia.
* Discusión sobre SQL y su relación con las operaciones de Pandas DataFrame.

# 2. Setup

In [1]:
import sqlite3 # a module in Python's standard library that provides an interface to the SQLite database.
import pandas as pd

In [2]:
url = "https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv"
titanic_data = pd.read_csv(url)

In [3]:
conn = sqlite3.connect(':memory:')
titanic_data.to_sql('titanic', conn, index=False)

887

**sqlite3.connect()** es una función que establece una conexión a una base de datos SQLite. Cuando se proporciona el argumento ':memory:', se le indica a SQLite que cree una nueva base de datos en la RAM. La principal ventaja de utilizar una base de datos en memoria es la velocidad.

**.to_sql()** es un método proporcionado por Pandas DataFrames que le permite escribir el contenido del DataFrame en una base de datos SQL.

El primer argumento 'titanic' es el nombre de la tabla que se creará en la base de datos SQLite.

El segundo argumento conn es el objeto de conexión que creamos anteriormente. Le indica al método .to_sql() dónde crear la tabla.

El argumento index=False le indica a Pandas que no escriba el índice del DataFrame como una columna separada en la base de datos. Si omitiera este argumento, obtendría una columna adicional llamada 'index' en su tabla SQL.

Función para ejecutar las queries (solamente ejecutarlo, no dará resultado)

In [4]:
# Function to run querys
def run_query(query, connection=conn):
    return pd.read_sql_query(query, connection)

# 3. SQL vs. Pandas

Para **SQL** nuestra tabla se llama *titanic*

Para **pandas** nuestro df se llama *titanic_data*

In [5]:
#Veo mis datos
titanic_data

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
...,...,...,...,...,...,...,...,...
882,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
883,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
884,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500
885,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000
886,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500



*   **Ver los nombres de 10 pasajeros**

In [6]:
# Usando SQL

run_query(
"""
SELECT Name
FROM titanic
limit 10
"""

 )

                                                Name
0                             Mr. Owen Harris Braund
1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2                              Miss. Laina Heikkinen
3        Mrs. Jacques Heath (Lily May Peel) Futrelle
4                            Mr. William Henry Allen
5                                    Mr. James Moran
6                             Mr. Timothy J McCarthy
7                      Master. Gosta Leonard Palsson
8   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9                 Mrs. Nicholas (Adele Achem) Nasser

In [7]:
# Usando Pandas
titanic_data.head(10)

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
5,0,3,Mr. James Moran,male,27.0,0,0,8.4583
6,0,1,Mr. Timothy J McCarthy,male,54.0,0,0,51.8625
7,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
8,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
9,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708

**¿Cuántas clases diferentes hay?**

In [8]:
# Usando SQL

run_query(
"""
SELECT DISTINCT Pclass
FROM titanic

"""
    )

   Pclass
0       3
1       1
2       2

In [9]:
# Usando Pandas

clases = titanic_data['Pclass'].unique()
print(clases)

[3 1 2]

**Mostrar los pasajeros ordenados por edad**

In [10]:
# Usando SQL

run_query(
"""
SELECT *
FROM titanic
ORDER BY age


"""
    )

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,1,3,Master. Assad Alexander Thomas,male,0.42,0,1,8.5167
1,1,2,Master. Viljo Hamalainen,male,0.67,1,1,14.5000
2,1,3,Miss. Helene Barbara Baclini,female,0.75,2,1,19.2583
3,1,3,Miss. Eugenie Baclini,female,0.75,2,1,19.2583
4,1,2,Master. Alden Gates Caldwell,male,0.83,0,2,29.0000
...,...,...,...,...,...,...,...,...
882,0,3,Mr. Patrick Connors,male,70.50,0,0,7.7500
883,0,1,Mr. George B Goldschmidt,male,71.00,0,0,34.6542
884,0,1,Mr. Ramon Artagaveytia,male,71.00,0,0,49.5042
885,0,3,Mr. Johan Svensson,male,74.00,0,0,7.7750
886,1,1,Mr. Algernon Henry Wilson Barkworth,male,80.00,0,0,30.0000

In [11]:
# Usando Pandas
Edad_ordenada = titanic_data.sort_values(by='Age')

print(Edad_ordenada)

     Survived  Pclass                                 Name     Sex    Age  \
799         1       3       Master. Assad Alexander Thomas    male   0.42
751         1       2             Master. Viljo Hamalainen    male   0.67
641         1       3                Miss. Eugenie Baclini  female   0.75
466         1       3         Miss. Helene Barbara Baclini  female   0.75
77          1       2         Master. Alden Gates Caldwell    male   0.83
..        ...     ...                                  ...     ...    ...
115         0       3                  Mr. Patrick Connors    male  70.50
490         0       1               Mr. Ramon Artagaveytia    male  71.00
95          0       1             Mr. George B Goldschmidt    male  71.00
847         0       3                   Mr. Johan Svensson    male  74.00
627         1       1  Mr. Algernon Henry Wilson Barkworth    male  80.00

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
799                        0                        1   8.5167
751                        1                        1  14.5000
641                        2                        1  19.2583
466                        2                        1  19.2583
77                         0                        2  29.0000
..                       ...                      ...      ...
115                        0                        0   7.7500
490                        0                        0  49.5042
95                         0                        0  34.6542
847                        0                        0   7.7750
627                        0                        0  30.0000

[887 rows x 8 columns]

**Mostrar los pasajeros que sobrevivieron**

In [12]:
# Usando SQL

run_query(
"""
SELECT *
FROM titanic
WHERE survived = 1

"""
    )

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
1,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
2,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
3,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
4,1,2,Mrs. Nicholas (Adele Achem) Nasser,female,14.0,1,0,30.0708
...,...,...,...,...,...,...,...,...
337,1,3,Miss. Adele Kiamie Najib,female,15.0,0,0,7.2250
338,1,1,Mrs. Thomas Jr (Lily Alexenia Wilson) Potter,female,56.0,0,1,83.1583
339,1,2,Mrs. William (Imanita Parrish Hall) Shelley,female,25.0,0,1,26.0000
340,1,1,Miss. Margaret Edith Graham,female,19.0,0,0,30.0000
341,1,1,Mr. Karl Howell Behr,male,26.0,0,0,30.0000

In [13]:
# Usando Pandas
sobrevivientes = titanic_data[titanic_data['Survived'] == 1]

print(sobrevivientes)

     Survived  Pclass                                               Name  \
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2           1       3                              Miss. Laina Heikkinen
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
8           1       3   Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
9           1       2                 Mrs. Nicholas (Adele Achem) Nasser
..        ...     ...                                                ...
871         1       3                           Miss. Adele Kiamie Najib
875         1       1       Mrs. Thomas Jr (Lily Alexenia Wilson) Potter
876         1       2        Mrs. William (Imanita Parrish Hall) Shelley
883         1       1                        Miss. Margaret Edith Graham
885         1       1                               Mr. Karl Howell Behr

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
1    female  38.0                        1                        0  71.2833
2    female  26.0                        0                        0   7.9250
3    female  35.0                        1                        0  53.1000
8    female  27.0                        0                        2  11.1333
9    female  14.0                        1                        0  30.0708
..      ...   ...                      ...                      ...      ...
871  female  15.0                        0                        0   7.2250
875  female  56.0                        0                        1  83.1583
876  female  25.0                        0                        1  26.0000
883  female  19.0                        0                        0  30.0000
885    male  26.0                        0                        0  30.0000

[342 rows x 8 columns]

**Mostrar los pasajeros que no sobrevivieron y tenían menos de 30 años**

In [14]:
# Usando SQL

run_query(
"""
SELECT *
FROM titanic
WHERE survived = 0 AND age < 30

"""
    )

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,0,3,Mr. James Moran,male,27.0,0,0,8.4583
2,0,3,Master. Gosta Leonard Palsson,male,2.0,3,1,21.0750
3,0,3,Mr. William Henry Saundercock,male,20.0,0,0,8.0500
4,0,3,Miss. Hulda Amanda Adolfina Vestrom,female,14.0,0,0,7.8542
...,...,...,...,...,...,...,...,...
300,0,3,Miss. Gerda Ulrika Dahlberg,female,22.0,0,0,10.5167
301,0,2,Mr. Frederick James Banfield,male,28.0,0,0,10.5000
302,0,3,Mr. Henry Jr Sutehall,male,25.0,0,0,7.0500
303,0,2,Rev. Juozas Montvila,male,27.0,0,0,13.0000
304,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500

In [15]:
# Usando Pandas
filtrado = titanic_data[(titanic_data['Survived'] == 0) & (titanic_data['Age'] < 30)]

print(filtrado)

     Survived  Pclass                                 Name     Sex   Age  \
0           0       3               Mr. Owen Harris Braund    male  22.0
5           0       3                      Mr. James Moran    male  27.0
7           0       3        Master. Gosta Leonard Palsson    male   2.0
12          0       3        Mr. William Henry Saundercock    male  20.0
14          0       3  Miss. Hulda Amanda Adolfina Vestrom  female  14.0
..        ...     ...                                  ...     ...   ...
878         0       3          Miss. Gerda Ulrika Dahlberg  female  22.0
879         0       2         Mr. Frederick James Banfield    male  28.0
880         0       3                Mr. Henry Jr Sutehall    male  25.0
882         0       2                 Rev. Juozas Montvila    male  27.0
884         0       3       Miss. Catherine Helen Johnston  female   7.0

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0                          1                        0   7.2500
5                          0                        0   8.4583
7                          3                        1  21.0750
12                         0                        0   8.0500
14                         0                        0   7.8542
..                       ...                      ...      ...
878                        0                        0  10.5167
879                        0                        0  10.5000
880                        0                        0   7.0500
882                        0                        0  13.0000
884                        1                        2  23.4500

[305 rows x 8 columns]



```
# Esto tiene formato de código
```

Mostrar pasajeron que tienen entre 30 y 50 años

In [18]:
# Usando SQL

run_query(
"""
SELECT *
FROM titanic
WHERE age BETWEEN 30 AND 50

"""
    )

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
1,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
2,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500
3,0,3,Mr. Anders Johan Andersson,male,39.0,1,5,31.2750
4,0,3,Mrs. Julius (Emelia Maria Vandemoortele) Vande...,female,31.0,1,0,18.0000
...,...,...,...,...,...,...,...,...
318,0,1,Mr. Frans Olof Carlsson,male,33.0,0,0,5.0000
319,0,3,Mr. Victor Vander Cruyssen,male,47.0,0,0,9.0000
320,0,3,Mr. Johann Markun,male,33.0,0,0,7.8958
321,0,3,Mrs. William (Margaret Norton) Rice,female,39.0,0,5,29.1250
322,0,3,Mr. Patrick Dooley,male,32.0,0,0,7.7500

In [21]:
# Usando Pandas
filtrado_2 = titanic_data[(titanic_data['Age'] <= 50) & (titanic_data['Age'] >= 30)]
filtrado_2[['Name','Age']]

                                                  Name   Age
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...  38.0
3          Mrs. Jacques Heath (Lily May Peel) Futrelle  35.0
4                              Mr. William Henry Allen  35.0
13                          Mr. Anders Johan Andersson  39.0
18   Mrs. Julius (Emelia Maria Vandemoortele) Vande...  31.0
..                                                 ...   ...
868                            Mr. Frans Olof Carlsson  33.0
869                         Mr. Victor Vander Cruyssen  47.0
877                                  Mr. Johann Markun  33.0
881                Mrs. William (Margaret Norton) Rice  39.0
886                                 Mr. Patrick Dooley  32.0

[323 rows x 2 columns]

**¿Cuántos pasajeros se llaman 'John'?**

In [24]:
# Usando SQL

run_query(
"""
SELECT *
FROM titanic
WHERE Name LIKE '%John%'

"""
    )

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
1,1,3,Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson,female,27.0,0,2,11.1333
2,0,2,Mrs. William John Robert (Dorothy Ann Wonnacot...,female,27.0,1,0,21.0000
3,0,3,Mr. William John Rogers,male,30.0,0,0,8.0500
4,1,2,Mrs. John T (Ada Julia Bone) Doling,female,34.0,0,1,23.0000
5,0,3,Mr. David John Barton,male,22.0,0,0,8.0500
6,0,2,Mr. William John Robert Turpin,male,29.0,1,0,21.0000
7,0,3,Mr. John Hatfield Cribb,male,44.0,0,1,16.1000
8,0,3,Mr. John Viktor Bengtsson,male,26.0,0,0,7.7750
9,1,3,Master. Frank John William Goldsmith,male,9.0,0,2,20.5250
10,0,1,Mr. John D Baumann,male,60.0,0,0,25.9250
11,1,3,Miss. Eleanor Ileen Johnson,female,1.0,1,1,11.1333
12,0,3,Mr. John Bourke,male,40.0,1,1,15.5000
13,0,3,Mr. John Henry Perkin,male,22.0,0,0,7.2500
14,1,2,Mr. William John Mellors,male,19.0,0,0,10.5000
15,0,3,Mr. John Hall Lovell,male,20.5,0,0,7.2500
16,0,3,Mr. William Cahoone Jr Johnson,male,19.0,0,0,0.0000
17,0,3,Mr. George John Jr Sage,male,20.0,8,2,69.5500
18,1,3,Mrs. Frank John (Emily Alice Brown) Goldsmith,female,31.0,1,1,20.5250
19,0,3,Mr. John Adams,male,26.0,0,0,8.0500
20,0,2,Mr. William John Matthews,male,30.0,0,0,13.0000
21,0,1,Mr. John Montgomery Smart,male,56.0,0,0,26.5500
22,0,1,Mr. John Farthing,male,49.0,0,0,221.7792
23,0,3,Mr. Frank John Goldsmith,male,33.0,1,1,20.5250
24,1,2,Master. John Morgan Jr Davies,male,8.0,1,1,36.7500
25,1,1,Mr. John Borland Jr Thayer,male,17.0,0,2,110.8833
26,0,3,Mr. John Simmons,male,40.0,0,0,8.0500
27,1,1,Mr. John Irwin Flynn,male,36.0,0,0,26.3875
28,0,3,Mr. Alfred George John Rush,male,16.0,0,0,8.0500
29,1,1,Mrs. John Borland (Marian Longstreth Morris) T...,female,39.0,1,1,110.8833
30,0,1,Mr. John Hugo Ross,male,36.0,0,0,40.1250
31,0,2,Mr. John Denzil Jarvis,male,47.0,0,0,15.0000
32,0,2,Mr. John Henry Chapman,male,37.0,1,0,26.0000
33,0,3,Mr. Alfred Johnson,male,49.0,0,0,0.0000
34,0,3,Mr. John Horgan,male,22.0,0,0,7.7500
35,0,3,Mr. David John Bowen,male,21.0,0,0,16.1000
36,0,3,Mrs. John (Catherine) Bourke,female,32.0,1,1,15.5000
37,0,1,Col. John Weir,male,60.0,0,0,26.5500
38,0,1,Mr. John Borland Thayer,male,49.0,1,1,110.8833
39,1,1,Mrs. John Jacob (Madeleine Talmadge Force) Astor,female,18.0,1,0,227.5250
40,0,3,Mr. Malkolm Joackim Johnson,male,33.0,0,0,7.7750
41,0,2,Mr. William John Berriman,male,23.0,0,0,13.0000
42,0,3,Mr. John Garfirth,male,23.0,0,0,14.5000
43,1,1,Mrs. John C (Anna Andrews) Hogeboom,female,51.0,1,0,77.9583
44,0,3,Mr. Andrew G Johnston,male,35.0,1,2,23.4500
45,0,3,Mr. John Fredrik Alexander Holm,male,43.0,0,0,6.4500
46,0,1,Jonkheer. John George Reuchlin,male,38.0,0,0,0.0000
47,0,3,Mr. John Flynn,male,36.0,0,0,6.9500
48,0,2,Rev. John Harper,male,28.0,0,1,33.0000
49,0,2,Mr. John William Gill,male,24.0,0,0,13.0000
50,1,3,Master. Harold Theodor Johnson,male,4.0,1,1,11.1333
51,0,3,Miss. Catherine Helen Johnston,female,7.0,1,2,23.4500

In [25]:
# Usando Pandas
john_count = titanic_data[titanic_data['Name'].str.contains('John')]

print(john_count[['Name']])
print("Cantidad:", len(john_count))

                                                  Name
1    Mrs. John Bradley (Florence Briggs Thayer) Cum...
8     Mrs. Oscar W (Elisabeth Vilhelmina Berg) Johnson
41   Mrs. William John Robert (Dorothy Ann Wonnacot...
44                             Mr. William John Rogers
97                 Mrs. John T (Ada Julia Bone) Doling
111                              Mr. David John Barton
116                     Mr. William John Robert Turpin
159                            Mr. John Hatfield Cribb
161                          Mr. John Viktor Bengtsson
164               Master. Frank John William Goldsmith
167                                 Mr. John D Baumann
171                        Miss. Eleanor Ileen Johnson
187                                    Mr. John Bourke
211                              Mr. John Henry Perkin
225                           Mr. William John Mellors
226                               Mr. John Hall Lovell
300                     Mr. William Cahoone Jr Johnson
322                            Mr. George John Jr Sage
326      Mrs. Frank John (Emily Alice Brown) Goldsmith
399                                     Mr. John Adams
416                          Mr. William John Matthews
464                          Mr. John Montgomery Smart
524                                  Mr. John Farthing
545                           Mr. Frank John Goldsmith
546                      Master. John Morgan Jr Davies
547                         Mr. John Borland Jr Thayer
560                                   Mr. John Simmons
569                               Mr. John Irwin Flynn
571                        Mr. Alfred George John Rush
578  Mrs. John Borland (Marian Longstreth Morris) T...
580                                 Mr. John Hugo Ross
583                             Mr. John Denzil Jarvis
591                             Mr. John Henry Chapman
594                                 Mr. Alfred Johnson
610                                    Mr. John Horgan
621                               Mr. David John Bowen
654                       Mrs. John (Catherine) Bourke
691                                     Col. John Weir
695                            Mr. John Borland Thayer
697   Mrs. John Jacob (Madeleine Talmadge Force) Astor
715                        Mr. Malkolm Joackim Johnson
729                          Mr. William John Berriman
756                                  Mr. John Garfirth
761                Mrs. John C (Anna Andrews) Hogeboom
779                              Mr. Andrew G Johnston
814                    Mr. John Fredrik Alexander Holm
818                     Jonkheer. John George Reuchlin
821                                     Mr. John Flynn
844                                   Rev. John Harper
860                              Mr. John William Gill
865                     Master. Harold Theodor Johnson
884                     Miss. Catherine Helen Johnston
Cantidad: 52